# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- develop
- release/*
pr:
- master
- develop
- release/*

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: Nuget
- group: AWS
- name: buildConfiguration
  value: 'Release'

stages:
- stage: build
  displayName: Build and test
  jobs:
  - job: Build
    steps:
    - task: gitversion/setup@0
      inputs:
        versionSpec: '5.x'

    - task: gitversion/execute@0

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        arguments: '--configuration $(buildConfiguration)'
  - job: Test
    steps:
    - task: DotNetCoreCLI@2
      displayName: Run tests
      inputs:
        command: 'test'
        projects: '**/*.Test[s].csproj'
- stage: publish
  displayName: Publish Nuget package (unstable)
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/develop'))
  jobs:
    - job: Publish
      steps:
        - task: DotNetCoreCLI@2
          inputs:
            command: 'pack'
            packagesToPack: '**/*.csproj;!**/*.Test[s].csproj'
            packDirectory: '$(Build.ArtifactStagingDirectory)/nuget'
            includesymbols: true
            versioningScheme: 'off'
        - task: DotnetGlobalToolInstaller@0
          inputs:
            name: 'sleet'
        - task: CmdLine@2
          condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/develop'))
          displayName: Push NuGet package to sleet (unstable)
          inputs:
            script: |
              sleet push -c sleet.json -s $(UnstableNugetFeedName) $(Build.ArtifactStagingDirectory)/nuget
          env:
            AWS_ACCESS_KEY_ID: $(AWS.AccessKeyID)
            AWS_SECRET_ACCESS_KEY: $(AWS.SecretAccessKey)
        - task: CmdLine@2
          condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
          displayName: Push NuGet package to sleet (stable)
          inputs:
            script: |
              sleet push -c sleet.json -s $(StableNugetFeedName) $(Build.ArtifactStagingDirectory)/nuget
          env:
            AWS_ACCESS_KEY_ID: $(AWS.AccessKeyID)
            AWS_SECRET_ACCESS_KEY: $(AWS.SecretAccessKey)
        


